# Generated by Django 4.2 on 2025-08-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.CharField(max_length=800)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('type_bien', models.CharField(max_length=100)),
                ('type_transaction', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surface', models.IntegerField()),
                ('urgence', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('degre_interet', models.CharField(max_length=100)),
                ('statut', models.CharField(default='Nouveau', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateTimeField()),
                ('lieu', models.CharField(max_length=100)),
                ('id_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lead.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Rappels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rappel', models.DateTimeField()),
                ('motif', models.CharField(max_length=100)),
                ('id_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lead.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('nbr_chambre', models.IntegerField()),
                ('id_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='Lead.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Lead_bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bien.bien')),
                ('id_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lead.lead')),
            ],
        ),
    ]
