# Generated by Django 4.2 on 2025-08-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='ancien_statut',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='nouveau_statut',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
