# Generated by Django 4.2 on 2025-08-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0003_commentaire_ancien_statut_commentaire_nouveau_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='ancien_statut',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenue',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='id_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='Lead.lead'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='nouveau_statut',
            field=models.CharField(max_length=100),
        ),
    ]
