# Generated by Django 4.2 on 2025-08-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0004_alter_commentaire_ancien_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='motif_perte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
