# Generated by Django 4.2 on 2025-08-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0005_commentaire_motif_perte'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='etat_bien',
            field=models.CharField(default='Neuf', max_length=100),
        ),
    ]
