# Generated by Django 4.2 on 2025-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0006_lead_etat_bien'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ascenseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='terrasse',
            field=models.BooleanField(default=False),
        ),
    ]
