# Generated by Django 4.2 on 2025-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0007_lead_ascenseur_lead_garage_lead_jardin_lead_terrasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='balcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='meuble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
