# Generated by Django 4.2 on 2025-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0008_lead_balcon_lead_meuble_lead_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
