# Generated by Django 4.2 on 2025-09-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0009_alter_lead_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='piscine',
            field=models.BooleanField(default=False),
        ),
    ]
