# Generated by Django 4.2 on 2025-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_bien', models.CharField(max_length=100)),
                ('type_transaction', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('superficie', models.IntegerField()),
                ('nbr_chambre', models.IntegerField()),
                ('etage', models.IntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('prop_nom', models.CharField(max_length=100)),
                ('prop_prenom', models.CharField(max_length=100)),
                ('prop_telephone', models.CharField(max_length=15, unique=True)),
                ('statut_commercial', models.CharField(default='Disponible', max_length=100)),
                ('degre_importance', models.CharField(max_length=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
