# Generated by Django 4.2 on 2025-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bien', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='etat_bien',
            field=models.CharField(default='Neuf', max_length=100),
        ),
    ]
