# Generated by Django 4.2 on 2025-08-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bien', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
