# Generated by Django 4.2 on 2025-08-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bien', '0005_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='ascenseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='terrasse',
            field=models.BooleanField(default=False),
        ),
    ]
