# Generated by Django 4.2 on 2025-09-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bien', '0006_bien_ascenseur_bien_garage_bien_jardin_bien_terrasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='balcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='meuble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
