# Generated by Django 4.2 on 2025-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bien', '0007_bien_balcon_bien_meuble_bien_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='prop_telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bien',
            name='reference',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
