# Generated by Django 4.2 on 2025-09-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bien', '0008_alter_bien_prop_telephone_alter_bien_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='piscine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bien',
            name='adresse',
            field=models.CharField(max_length=5000),
        ),
    ]
